access-type:
  label: "'Access Type'"
  slices:
    epon:
      color: "'#42f566'"
      filter: InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.WANAccessType
        = "EPON"
      label: "'EPON'"
    ethernet:
      color: "'#00214a'"
      filter: InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.WANAccessType
        = "Ethernet"
      label: "'Ethernet'"
    gpon:
      color: "'#0266e0'"
      filter: InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.WANAccessType
        = "GPON"
      label: "'GPON'"
optical-rx-power-short:
  label: "'RX Power'"
  slices:
    0_rxNa:
      color: "'#ffffff'"
      filter: VirtualParameters.OpticalRXPower = "N/A"
    1_rxTooStrong:
      color: "'#f28f00'"
      filter: VirtualParameters.OpticalRXPower > -10 AND
        VirtualParameters.OpticalRXPower <> "N/A"
    2_rxExcellent:
      color: "'#0266e0'"
      filter: VirtualParameters.OpticalRXPower <= -10 AND
        VirtualParameters.OpticalRXPower > -20
    3_rxGood:
      color: "'#1fde5a'"
      filter: VirtualParameters.OpticalRXPower <= -20 AND
        VirtualParameters.OpticalRXPower >= -25
    4_rxBad:
      color: "'#ff5252'"
      filter: VirtualParameters.OpticalRXPower < -25 AND
        VirtualParameters.OpticalRXPower <> "N/A"
optical-temperature-short:
  label: "'Optical Temperature'"
  slices:
    0_tempNa:
      color: "'#ffffff'"
      filter: VirtualParameters.OpticalTemperature = "N/A"
    1_Good:
      color: "'#1fde5a'"
      filter: VirtualParameters.OpticalTemperature < 45 AND
        VirtualParameters.OpticalTemperature <> "N/A"
    2_Ok:
      color: "'#f28f00'"
      filter: VirtualParameters.OpticalTemperature >= 45 AND
        VirtualParameters.OpticalTemperature <= 60
    3_Bad:
      color: "'#ff5252'"
      filter: VirtualParameters.OpticalTemperature > 60 AND
        VirtualParameters.OpticalTemperature <> "N/A"
online-short:
  label: "'Online status'"
  slices:
    0_online:
      color: "'#1fde5a'"
      filter: Events.Inform > NOW() - 15 * 60 * 1000
    1_offline_lt_1d:
      color: "'#f28f00'"
      filter: Events.Inform <= NOW() - 15 * 60 * 1000 AND Events.Inform > NOW() - 24 *
        60 * 60 * 1000
    2_offline_gt_1d:
      color: "'#ff5252'"
      filter: Events.Inform <= NOW() - 24 * 60 * 60 * 1000
optical-rx-power:
  label: "'RX Power'"
  slices:
    0_rxNa:
      color: "'#ffffff'"
      filter: VirtualParameters.OpticalRXPower = "N/A"
      label: "'N/A'"
    1_rxTooStrong:
      color: "'#f28f00'"
      filter: VirtualParameters.OpticalRXPower > -10 AND
        VirtualParameters.OpticalRXPower <> "N/A"
      label: "'Too Strong'"
    2_rxExcellent:
      color: "'#0266e0'"
      filter: VirtualParameters.OpticalRXPower <= -10 AND
        VirtualParameters.OpticalRXPower > -20
      label: "'Excellent'"
    3_rxGood:
      color: "'#1fde5a'"
      filter: VirtualParameters.OpticalRXPower <= -20 AND
        VirtualParameters.OpticalRXPower >= -25
      label: "'Good'"
    4_rxBad:
      color: "'#ff5252'"
      filter: VirtualParameters.OpticalRXPower < -25 AND
        VirtualParameters.OpticalRXPower <> "N/A"
      label: "'Bad'"
optical-temperature:
  label: "'Optical Temperature'"
  slices:
    0_tempNa:
      color: "'#ffffff'"
      filter: VirtualParameters.OpticalTemperature = "N/A"
      label: "'N/A'"
    1_Good:
      color: "'#1fde5a'"
      filter: VirtualParameters.OpticalTemperature < 45 AND
        VirtualParameters.OpticalTemperature <> "N/A"
      label: "'Cool'"
    2_Ok:
      color: "'#f28f00'"
      filter: VirtualParameters.OpticalTemperature >= 45 AND
        VirtualParameters.OpticalTemperature <= 60
      label: "'Warm'"
    3_Bad:
      color: "'#ff5252'"
      filter: VirtualParameters.OpticalTemperature > 60 AND
        VirtualParameters.OpticalTemperature <> "N/A"
      label: "'Hot'"
total-stations:
  label: "'Total Stations'"
  slices:
    0_Free:
      color: "'#ffffff'"
      filter: VirtualParameters.TotalStations < 1
      label: "'0 Stations'"
    1_Light:
      color: "'#1fde5a'"
      filter: VirtualParameters.TotalStations >= 1 AND VirtualParameters.TotalStations
        <= 5
      label: "'1-5 Stations'"
    2_Ok:
      color: "'#f28f00'"
      filter: VirtualParameters.TotalStations >= 6 AND VirtualParameters.TotalStations
        <= 10
      label: "'6-10 Stations'"
    3_Crowded:
      color: "'#ff5252'"
      filter: VirtualParameters.TotalStations > 10
      label: "'10+ Stations'"
device-uptime:
  label: "'Device Uptime'"
  slices:
    0_under1h:
      color: "'#1fde5a'"
      filter: InternetGatewayDevice.DeviceInfo.UpTime <= 3600
      label: "'Uptime <1h'"
    1_under1d:
      color: "'#d1de1f'"
      filter: InternetGatewayDevice.DeviceInfo.UpTime > 3600 AND
        InternetGatewayDevice.DeviceInfo.UpTime <= 86400
      label: "'Uptime <1d'"
    2_under1w:
      color: "'#f28f00'"
      filter: InternetGatewayDevice.DeviceInfo.UpTime > 86400 AND
        InternetGatewayDevice.DeviceInfo.UpTime <= 604800
      label: "'Uptime <1w'"
    3_under1mo:
      color: "'#ff5252'"
      filter: InternetGatewayDevice.DeviceInfo.UpTime > 604800 AND
        InternetGatewayDevice.DeviceInfo.UpTime <= 2592000
      label: "'Uptime <1mo'"
    4_over1mo:
      color: "'#7b1fa2'"
      filter: InternetGatewayDevice.DeviceInfo.UpTime > 2592000
      label: "'Uptime >1mo'"
online:
  label: "'Last Inform'"
  slices:
    0_online:
      color: "'#1fde5a'"
      filter: Events.Inform > NOW() - 15 * 60 * 1000
      label: "'Online'"
    1_offline_lt_1d:
      color: "'#f28f00'"
      filter: Events.Inform <= NOW() - 15 * 60 * 1000 AND Events.Inform > NOW() - 24 *
        60 * 60 * 1000
      label: "'Offline <1d'"
    2_offline_gt_1d:
      color: "'#ff5252'"
      filter: Events.Inform <= NOW() - 24 * 60 * 60 * 1000
      label: "'Offline >1d'"
registered:
  label: "'Registered'"
  slices:
    0_registered_lt_1d:
      color: "'#1fde5a'"
      filter: Events.Registered > NOW() - 24 * 60 * 60 * 1000
      label: "'Registered <1d'"
    1_registered_lt_30d:
      color: "'#f28f00'"
      filter: Events.Registered <= NOW() - 24 * 60 * 60 * 1000 AND Events.Registered >
        NOW() - 30 * 24 * 60 * 60 * 1000
      label: "'Registered <30d'"
    2_registered_gt_30d:
      color: "'#ff5252'"
      filter: Events.Registered <= NOW() - 30 * 24 * 60 * 60 * 1000
      label: "'Registered >30d'"
manufacturer:
  label: "'Manufacturer'"
  slices:
    CIOT:
      color: "'#42f566'"
      filter: VirtualParameters.KnownManufacturer = "CIOT"
      label: "'CIOT'"
    CMDC:
      color: "'#0266e0'"
      filter: VirtualParameters.KnownManufacturer = "CMDC"
      label: "'CMDC'"
    FiberHome:
      color: "'#00214a'"
      filter: VirtualParameters.KnownManufacturer = "FiberHome"
      label: "'FiberHome'"
    GGCL:
      color: "'#0b4a00'"
      filter: VirtualParameters.KnownManufacturer = "GGCL"
      label: "'GGCL'"
    HWTC:
      color: "'#9942f5'"
      filter: VirtualParameters.KnownManufacturer = "HWTC"
      label: "'HWTC'"
    Huawei:
      color: "'#4287f5'"
      filter: VirtualParameters.KnownManufacturer = "Huawei Technologies Co., Ltd"
      label: "'Huawei'"
    NNSC:
      color: "'#4254f5'"
      filter: VirtualParameters.KnownManufacturer = "NNSC"
      label: "'NNSC'"
    XSFG:
      color: "'#42f5f2'"
      filter: VirtualParameters.KnownManufacturer = "XSFG"
      label: "'XSFG'"
    YEKF:
      color: "'#f542e5'"
      filter: VirtualParameters.KnownManufacturer = "YEKF"
      label: "'YEKF'"
    ZICG:
      color: "'#f54278'"
      filter: VirtualParameters.KnownManufacturer = "ZICG"
      label: "'ZICG'"
    ZTE:
      color: "'#e0a102'"
      filter: VirtualParameters.KnownManufacturer = "ZTE"
      label: "'ZTE'"
    ZTEG:
      color: "'#f5b642'"
      filter: VirtualParameters.KnownManufacturer = "ZTEG"
      label: "'ZTEG'"
    ZXIC:
      color: "'#42f545'"
      filter: VirtualParameters.KnownManufacturer = "ZXIC"
      label: "'ZXIC'"
    zz_Other:
      color: "'#ffffff'"
      filter: VirtualParameters.KnownManufacturer = "Other"
      label: "'Other'"
product-class:
  label: "'Product Class'"
  slices:
    F450:
      color: "'#e0a102'"
      filter: VirtualParameters.KnownProductClass = "ZXHN F450(EPON ONU)"
      label: "'F450'"
    F460:
      color: "'#a1e002'"
      filter: VirtualParameters.KnownProductClass = "F460"
      label: "'F460'"
    F609:
      color: "'#02a1e0'"
      filter: VirtualParameters.KnownProductClass = "F609"
      label: "'F609'"
    F650:
      color: "'#e002a1'"
      filter: VirtualParameters.KnownProductClass = "F650"
      label: "'F650'"
    F663NV3A:
      color: "'#a102e0'"
      filter: VirtualParameters.KnownProductClass = "F663NV3a" OR VirtualParameters.KnownProductClass
        = "F663NV3A"
      label: "'F663NV3A'"
    F663NV9:
      color: "'#e0a101'"
      filter: VirtualParameters.KnownProductClass = "F663NV9"
      label: "'F663NV9'"
    F670:
      color: "'#01e0a1'"
      filter: VirtualParameters.KnownProductClass = "F670"
      label: "'F670'"
    F670L:
      color: "'#a101e0'"
      filter: VirtualParameters.KnownProductClass = "F670L"
      label: "'F670L'"
    G663:
      color: "'#0b4a00'"
      filter: VirtualParameters.KnownProductClass = "G663 XPON" OR VirtualParameters.KnownProductClass
        = "G663-XPON"
      label: "'G663'"
    G665:
      color: "'#4a0b00'"
      filter: VirtualParameters.KnownProductClass = "G665 XPON"
      label: "'G665'"
    G680L:
      color: "'#000b4a'"
      filter: VirtualParameters.KnownProductClass = "G680L XPON"
      label: "'G680L'"
    G99:
      color: "'#4a000b'"
      filter: VirtualParameters.KnownProductClass = "G99 XPON"
      label: "'G99'"
    GM219:
      color: "'#4a4a00'"
      filter: VirtualParameters.KnownProductClass = "GM219"
      label: "'GM219'"
    GM220-S:
      color: "'#42f566'"
      filter: VirtualParameters.KnownProductClass = "GM220-S" OR VirtualParameters.KnownProductClass
        = "GM220-S XPON"
      label: "'GM220-S'"
    GM630:
      color: "'#42f5bc'"
      filter: VirtualParameters.KnownProductClass = "GM630"
      label: "'GM630'"
    H1s-3:
      color: "'#0266e0'"
      filter: VirtualParameters.KnownProductClass = "H1s-3"
      label: "'H1s-3'"
    HG6145D2:
      color: "'#e04242'"
      filter: VirtualParameters.KnownProductClass = "HG6145D2"
      label: "'HG6145D2'"
    HG6245N:
      color: "'#42e042'"
      filter: VirtualParameters.KnownProductClass = "HG6245N"
      label: "'HG6245N'"
    HG8145V5:
      color: "'#4242e0'"
      filter: VirtualParameters.KnownProductClass = "HG8145V5"
      label: "'HG8145V5'"
    HG8245A:
      color: "'#428700'"
      filter: VirtualParameters.KnownProductClass = "HG8245A"
      label: "'HG8245A'"
    HG8245H:
      color: "'#874200'"
      filter: VirtualParameters.KnownProductClass = "HG8245H"
      label: "'HG8245H'"
    HG8245H5:
      color: "'#008742'"
      filter: VirtualParameters.KnownProductClass = "HG8245H5"
      label: "'HG8245H5'"
    HG8546M:
      color: "'#420087'"
      filter: VirtualParameters.KnownProductClass = "HG8546M"
      label: "'HG8546M'"
    HS8145C5:
      color: "'#4287f5'"
      filter: VirtualParameters.KnownProductClass = "HS8145C5"
      label: "'HS8145C5'"
    MQ220:
      color: "'#004a37'"
      filter: VirtualParameters.KnownProductClass = "MQ220"
      label: "'MQ220'"
    XSF609:
      color: "'#37004a'"
      filter: VirtualParameters.KnownProductClass = "XSF609"
      label: "'XSF609'"
    Other:
      color: "'#ffffff'"
      filter: VirtualParameters.KnownProductClass = "Other"
      label: "'Other'"
