group02:
  label: "''"
  charts:
    - "'device-uptime'"
    - "'total-stations'"
    - "'optical-rx-power'"
    - "'optical-temperature'"
group03:
  label: "''"
  charts:
    - "'product-class'"
    - "'manufacturer'"
group01:
  label: "''"
  charts:
    - "'online'"
    - "'registered'"
    - "'access-type'"
